#!/usr/bin/env python3
"""
Train machine learning models for the IDS/IPS system.

This script consumes the artifacts generated by preprocess_kdd.py (features, labels,
preprocessor + label encoders) and emits the trained pickle/PyTorch models alongside
confusion matrices for quick inspection.
"""

import argparse
import pickle
import random
from pathlib import Path
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

BASE_DIR = Path(__file__).parent
DEFAULT_DATA_DIR = BASE_DIR / "data"
DEFAULT_MODEL_DIR = Path("models")

# Define neural network model
class DNNModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(DNNModel, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, num_classes)
        self.dropout = nn.Dropout(0.2)
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.dropout(out)
        out = self.fc3(out)
        return out

def parse_args():
    parser = argparse.ArgumentParser(description="Train ML models on preprocessed IDS datasets.")
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=DEFAULT_DATA_DIR,
        help="Directory containing X_train.npy, label encoders, etc. (default: models/training_scripts/data)",
    )
    parser.add_argument(
        "--model-dir",
        type=Path,
        default=DEFAULT_MODEL_DIR,
        help="Directory where trained models and plots will be saved (default: ./models)",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=None,
        help="Optional cap on the number of samples from X_train/X_test for quick iterations.",
    )
    parser.add_argument(
        "--rf-estimators",
        type=int,
        default=200,
        help="Number of estimators in the RandomForest classifier (default: 200).",
    )
    parser.add_argument(
        "--dnn-epochs",
        type=int,
        default=20,
        help="Number of epochs to train the DNN (default: 20).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42).",
    )
    return parser.parse_args()


def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_data(data_dir: Path, max_samples: Optional[int] = None):
    """Load preprocessed data artifacts from disk."""
    data_dir = data_dir.expanduser()
    if not data_dir.exists():
        raise FileNotFoundError(f"Preprocessed data directory not found: {data_dir}")

    def _load_array(name: str):
        path = data_dir / name
        if not path.exists():
            raise FileNotFoundError(f"Required artifact missing: {path}")
        return np.load(path)

    X_train = _load_array("X_train.npy")
    X_test = _load_array("X_test.npy")
    y_binary_train = _load_array("y_binary_train.npy")
    y_binary_test = _load_array("y_binary_test.npy")
    y_category_train = _load_array("y_category_train.npy")
    y_category_test = _load_array("y_category_test.npy")

    with open(data_dir / "preprocessor.pkl", "rb") as f:
        preprocessor = pickle.load(f)
    with open(data_dir / "le_binary.pkl", "rb") as f:
        le_binary = pickle.load(f)
    with open(data_dir / "le_category.pkl", "rb") as f:
        le_category = pickle.load(f)

    if max_samples:
        X_train = X_train[:max_samples]
        y_binary_train = y_binary_train[:max_samples]
        y_category_train = y_category_train[:max_samples]
        X_test = X_test[:max_samples]
        y_binary_test = y_binary_test[:max_samples]
        y_category_test = y_category_test[:max_samples]
        print(f"Training on subset of {len(X_train)} samples (max-samples={max_samples}).")

    return (
        X_train,
        X_test,
        y_binary_train,
        y_binary_test,
        y_category_train,
        y_category_test,
        preprocessor,
        le_binary,
        le_category,
    )

def train_random_forest(
    X_train,
    X_test,
    y_train,
    y_test,
    n_estimators: int,
    plot_dir: Path,
):
    """Train Random Forest model."""
    print("Training Random Forest model...")
    rf = RandomForestClassifier(n_estimators=n_estimators, random_state=42, n_jobs=-1)
    rf.fit(X_train, y_train)

    y_pred = rf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Random Forest Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title("Random Forest Confusion Matrix")
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plot_dir.mkdir(parents=True, exist_ok=True)
    plt.savefig(plot_dir / "rf_confusion_matrix.png")
    plt.close()

    return rf

def train_dnn(
    X_train,
    X_test,
    y_train,
    y_test,
    input_size,
    num_classes,
    epochs: int,
    plot_dir: Path,
):
    """Train Deep Neural Network model."""
    print("Training Deep Neural Network model...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    X_train_tensor = torch.FloatTensor(X_train).to(device)
    y_train_tensor = torch.LongTensor(y_train).to(device)
    X_test_tensor = torch.FloatTensor(X_test).to(device)
    y_test_tensor = torch.LongTensor(y_test).to(device)

    hidden_size = 128
    model = DNNModel(input_size, hidden_size, num_classes).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    batch_size = 64

    train_dataset = torch.utils.data.TensorDataset(X_train_tensor, y_train_tensor)
    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    print("Training DNN...")
    for epoch in range(epochs):
        epoch_loss = 0.0
        for inputs, labels in train_loader:
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        if (epoch + 1) % 5 == 0 or epoch == epochs - 1:
            avg_loss = epoch_loss / max(1, len(train_loader))
            print(f"Epoch {epoch+1}/{epochs} - loss: {avg_loss:.4f}")

    model.eval()
    with torch.no_grad():
        outputs = model(X_test_tensor)
        _, predicted = torch.max(outputs.data, 1)
        accuracy = (predicted == y_test_tensor).sum().item() / len(y_test_tensor)
        print(f"DNN Accuracy: {accuracy:.4f}")

    print("Classification Report:")
    print(classification_report(y_test_tensor.cpu().numpy(), predicted.cpu().numpy()))

    cm = confusion_matrix(y_test_tensor.cpu().numpy(), predicted.cpu().numpy())
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
    plt.title("DNN Confusion Matrix")
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plot_dir.mkdir(parents=True, exist_ok=True)
    plt.savefig(plot_dir / "dnn_confusion_matrix.png")
    plt.close()

    return model

def main():
    args = parse_args()
    set_seed(args.seed)

    (
        X_train,
        X_test,
        y_binary_train,
        y_binary_test,
        y_category_train,
        y_category_test,
        preprocessor,
        le_binary,
        le_category,
    ) = load_data(args.data_dir, args.max_samples)

    model_dir = args.model_dir
    if not model_dir.is_absolute():
        model_dir = (Path.cwd() / model_dir).resolve()
    model_dir.mkdir(parents=True, exist_ok=True)

    rf_model = train_random_forest(
        X_train,
        X_test,
        y_binary_train,
        y_binary_test,
        n_estimators=args.rf_estimators,
        plot_dir=model_dir,
    )

    input_size = X_train.shape[1]
    num_classes = len(le_category.classes_)
    dnn_model = train_dnn(
        X_train,
        X_test,
        y_category_train,
        y_category_test,
        input_size,
        num_classes,
        epochs=args.dnn_epochs,
        plot_dir=model_dir,
    )

    print(f"Saving models to {model_dir} ...")
    with open(model_dir / "attack_classifier_rf.pkl", "wb") as f:
        pickle.dump(rf_model, f)
    torch.save(dnn_model.state_dict(), model_dir / "attack_classifier_dnn.pth")

    with open(model_dir / "preprocessor.pkl", "wb") as f:
        pickle.dump(preprocessor, f)
    with open(model_dir / "le_binary.pkl", "wb") as f:
        pickle.dump(le_binary, f)
    with open(model_dir / "le_category.pkl", "wb") as f:
        pickle.dump(le_category, f)

    print("Training complete!")

if __name__ == "__main__":
    main()
